### ISSUE TITLE
Użytkownik może like'ować tego samego posta wiele razy

### ISSUE THREAD

**Issue by Macintoshx** [Lupi-Stole-My-Code/NZI-Project#24]
jw

**Comment by Mayumu** [comment]
Po zmianach ScoreService nie da się tego sprawdzać -> metoda getScoresByElem nie zwraca jaki użytkownik wykonał score.

**Comment by Macintoshx** [comment]
zaraz to zmienie.

**Comment by Macintoshx** [comment]
done
